import type { Metadata } from "next";
import { Rammetto_One } from "next/font/google";
import "./globals.css";

const rammetteOne = Rammetto_One({
  variable: "--font-rammette-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rammetteOne.variable}  antialiased`}>
        <div className="min-h-screen h-full w-full p-10 md:p-6 sm:p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
