import "./globals.css";
import "@fontsource/rammetto-one";

export const metadata = {
  title: "Selenium Testing application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="min-h-screen h-full w-full p-10 md:p-6 sm:p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
