name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      # Create .env file for Next.js
      - name: Set environment variables
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env

      - name: Print environment variable (for debugging)
        run: cat .env

      - name: Build
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Selenium Tests
        run: npm run test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports
